export const products = [
  {
    _id: '1',
    name: 'Backpack',
    image: '/images/backpack.jpg',
    brand: 'aaaa',
    typeOfShare: 'give away',
    gender: 'neutral',
    condition: 'new',
    description: '',
  },
  {
    _id: '2',
    name: 'Bicycle',
    image: '/images/bicycle.jpg',
    brand: 'aaaa',
    typeOfShare: 'lend',
    gender: 'neutral',
    condition: 'used - needs some repairs',
    description: '',
  },
  {
    _id: '3',
    name: 'Mechanical Keyboard',
    image: '/images/keyboard.jpg',
    brand: 'aaaa',
    typeOfShare: 'exchange',
    gender: 'neutral',
    condition: 'used - good condition',
    description: '',
  },
  {
    _id: '4',
    name: 'PS4 Controller',
    image: '/images/ps4-controller.jpg',
    brand: 'aaaa',
    typeOfShare: 'exchange',
    gender: 'neutral',
    condition: 'used - good condition',
    description: '',
  },
  {
    _id: '5',
    name: 'Sunglasses',
    image: '/images/sunglasses.jpg',
    brand: 'aaaa',
    typeOfShare: 'give away',
    gender: 'female',
    condition: 'used - good condition',
    description: '',
  },
  {
    _id: '6',
    name: 'HeadSet',
    image: '/images/wired-headset.jpg',
    brand: 'aaaa',
    typeOfShare: 'exchange',
    gender: 'neutral',
    condition: 'used - good condition',
    description: '',
  },
];
